# Generated by Django 2.2 on 2021-05-30 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('date_joined', models.DateField()),
                ('total_shares', models.IntegerField(default=0)),
                ('total_welfare', models.IntegerField(default=0)),
                ('total_savings', models.IntegerField(default=0)),
                ('total_withdraw', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MemberDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('shares', models.IntegerField(default=0)),
                ('welfare', models.IntegerField(default=0)),
                ('savings', models.IntegerField(default=0)),
                ('withdraw', models.IntegerField(default=0)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Members')),
            ],
        ),
    ]
