# Generated by Django 2.2 on 2021-05-31 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_memberdetail_fines'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='total_fines',
            field=models.IntegerField(default=0),
        ),
    ]
