# Generated by Django 2.2 on 2021-05-31 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_members_total_fines'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberdetail',
            name='transaction_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
