# Generated by Django 2.2 on 2021-06-01 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_memberdetail_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberdetail',
            name='fine_type',
            field=models.CharField(choices=[('general_meeting_fine', 'General Meeting'), ('weekly_meeting_fine', 'Weekly Meeting'), ('late_fine', 'Late'), ('uniform_fine', 'Uniform'), ('minimum_savings_fine', 'Minimum Savings')], max_length=255, null=True),
        ),
    ]
