# Generated by Django 2.2 on 2021-06-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210601_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberdetail',
            name='fine_type',
            field=models.CharField(blank=True, choices=[('General_Meeting', 'General Meeting'), ('Weekly_Meeting', 'Weekly Meeting'), ('Late', 'Late'), ('Uniform', 'Uniform'), ('Minimum_Savings', 'Minimum Savings')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='memberdetail',
            name='transaction_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
