# Generated by Django 3.2 on 2022-08-16 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20220813_1731'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='members',
            options={'verbose_name': 'Member', 'verbose_name_plural': 'Members'},
        ),
        migrations.RenameField(
            model_name='members',
            old_name='total_fines',
            new_name='fines',
        ),
        migrations.RenameField(
            model_name='members',
            old_name='total_savings',
            new_name='savings',
        ),
        migrations.RenameField(
            model_name='members',
            old_name='total_shares',
            new_name='shares',
        ),
        migrations.RenameField(
            model_name='members',
            old_name='total_welfare',
            new_name='welfare',
        ),
        migrations.RenameField(
            model_name='members',
            old_name='total_withdraw',
            new_name='withdraw',
        ),
    ]
