# Generated by Django 3.2 on 2022-08-16 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20220816_2203'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Members',
            new_name='Member',
        ),
        migrations.RenameModel(
            old_name='MemberDetail',
            new_name='Transaction',
        ),
    ]
