# Generated by Django 3.2 on 2022-08-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_member_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={},
        ),
        migrations.AlterField(
            model_name='member',
            name='date_joined',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='fine_type',
            field=models.CharField(blank=True, choices=[('General Meeting', 'General Meeting'), ('Weekly Meeting', 'Weekly Meeting'), ('Late', 'Late'), ('Uniform', 'Uniform'), ('Minimum Savings', 'Minimum Savings')], max_length=255, null=True),
        ),
    ]
