# Generated by Django 3.2 on 2022-08-26 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_transactiontype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiontype',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
