# Generated by Django 3.2 on 2022-08-26 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_transaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiontype',
            name='share_pay',
            field=models.BooleanField(default=False),
        ),
    ]
