# Generated by Django 3.2 on 2022-08-26 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_member_all_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tulinaawe',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('reason', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TulinaaweContributor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tulinaawe')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.member')),
            ],
        ),
    ]
