# Generated by Django 3.2 on 2022-08-26 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20220826_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tulinaawe',
            old_name='reason',
            new_name='description',
        ),
    ]
