# Generated by Django 3.2 on 2022-08-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_rename_reason_tulinaawe_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tulinaawe',
            name='amount_contributed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tulinaawe',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
