# Generated by Django 3.2 on 2022-08-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20220826_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='tulinaawe',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
