# Generated by Django 3.2 on 2022-09-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_tulinaawe_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tulinaawe',
            old_name='amount_contributed',
            new_name='total_amount_contributed',
        ),
        migrations.AddField(
            model_name='tulinaawecontributor',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
