# Generated by Django 3.2 on 2022-09-25 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_tulinaawecontributor_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tulinaawe',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Tulinaawe'},
        ),
        migrations.AddField(
            model_name='transaction',
            name='other',
            field=models.IntegerField(default=0),
        ),
    ]
