# Generated by Django 3.2 on 2022-09-25 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_transaction_other_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='other_reason',
            field=models.TextField(default='Other Reason'),
        ),
    ]
