# Generated by Django 3.2 on 2022-09-25 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_member_others'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='others',
            new_name='other',
        ),
    ]
