# Generated by Django 3.2 on 2022-12-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_remove_member_full_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='full_names',
            field=models.CharField(default='', max_length=255),
        ),
    ]
