# Generated by Django 3.2 on 2022-12-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_member_full_names'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tulinaawe',
            options={},
        ),
        migrations.RenameField(
            model_name='tulinaawe',
            old_name='date',
            new_name='date_due',
        ),
        migrations.AddField(
            model_name='tulinaawe',
            name='date_created',
            field=models.DateTimeField(null=True),
        ),
    ]
