# Generated by Django 3.2 on 2022-12-05 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_alter_tulinaawe_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tulinaawe',
            name='date_created',
        ),
    ]
