# Generated by Django 3.2 on 2022-12-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_remove_tulinaawe_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='tulinaawe',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
