# Generated by Django 3.2 on 2022-12-06 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_auto_20221206_0514'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='amount_paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loan',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
