# Generated by Django 3.2 on 2022-12-06 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_auto_20221206_0516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanpayment',
            old_name='payment',
            new_name='amount',
        ),
    ]
