# Generated by Django 3.2 on 2022-12-06 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_rename_payment_loanpayment_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='balance',
        ),
    ]
