# Generated by Django 3.2 on 2022-12-16 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_auto_20221216_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('receipt_no', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('cost_price', models.IntegerField(blank=True, null=True)),
                ('total_value', models.IntegerField(default=0)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.expense')),
            ],
        ),
    ]
