# Generated by Django 3.2 on 2022-12-25 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_expense_items_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='total_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='expense',
            name='items_no',
            field=models.IntegerField(default=0),
        ),
    ]
