# Generated by Django 3.2 on 2022-12-25 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_auto_20221225_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseitem',
            name='cost_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='expenseitem',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
