# Generated by Django 3.2 on 2022-12-25 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_alter_expense_receipt_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='_from',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='expense',
            name='_to',
            field=models.CharField(default='', max_length=255),
        ),
    ]
