# Generated by Django 3.2 on 2022-12-25 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_auto_20221225_0540'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='non_member_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='_from',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='expense',
            name='_to',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
