# Generated by Django 3.2 on 2022-12-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='ineterest',
            field=models.IntegerField(default=0),
        ),
    ]
