# Generated by Django 3.2 on 2022-12-25 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_loan_ineterest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='ineterest',
            new_name='interest',
        ),
    ]
