# Generated by Django 3.2 on 2023-01-12 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_auto_20230112_0915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='identication_no',
            new_name='identification_no',
        ),
    ]
