# Generated by Django 3.2 on 2023-01-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_rename_identication_no_member_identification_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='date_of_employment',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='employer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='member',
            name='employment_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='member',
            name='position_in_employment',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='member',
            name='staff_number',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
