# Generated by Django 3.2 on 2023-01-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_auto_20230112_1708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='memberbership_approved_by',
            new_name='membership_approved_by',
        ),
        migrations.AddField(
            model_name='member',
            name='addmitted_by_1_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='addmitted_by_2_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='membership_approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='system_approval_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
