# Generated by Django 3.2 on 2023-01-12 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0063_auto_20230112_1819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='addmitted_by_1_date',
            new_name='admitted_by_1_date',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='addmitted_by_2_date',
            new_name='admitted_by_2_date',
        ),
    ]
