# Generated by Django 3.2 on 2023-01-12 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0064_auto_20230112_1827'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NominessForDeposits',
            new_name='NomineesForDeposits',
        ),
    ]
