# Generated by Django 3.2 on 2023-01-12 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0065_rename_nominessfordeposits_nomineesfordeposits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='amount_in_words',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
