# Generated by Django 3.2 on 2023-01-12 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0066_alter_member_amount_in_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='data_date_capture',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='effective_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
