# Generated by Django 3.2 on 2023-01-28 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0068_alter_transaction_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='non_member_name',
            new_name='member_name',
        ),
        migrations.AddField(
            model_name='loan',
            name='comitee_member_1_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='comitee_member_2_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='comitee_member_3_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='comittee_member_1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='loan',
            name='comittee_member_2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='loan',
            name='comittee_member_3',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='loan',
            name='date_when_required',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='guarantor_1_membership_no',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='loan',
            name='guarantor_1_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='loan',
            name='guarantor_2_membership_no',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='loan',
            name='guarantor_2_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='loan',
            name='location_of_business',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='loan',
            name='purpose_of_loan',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='loan',
            name='residential_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='loan',
            name='savings_account_no',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='loan',
            name='security_1_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='loan',
            name='security_1_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='loan',
            name='security_1_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loan',
            name='security_2_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='loan',
            name='security_2_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='loan',
            name='security_2_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loan',
            name='source_of_loan_repayment',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='loan',
            name='value_of_savings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loan',
            name='value_of_shares',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='loan',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.member'),
        ),
    ]
