# Generated by Django 3.2 on 2023-01-28 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0069_auto_20230128_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='member_name',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
