# Generated by Django 3.2 on 2023-01-28 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0070_alter_loan_member_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='amount_in_words',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
