# Generated by Django 3.2 on 2023-01-28 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0071_loan_amount_in_words'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='comitee_member_1_date',
            new_name='commitee_member_1_date',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='comitee_member_2_date',
            new_name='commitee_member_2_date',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='comitee_member_3_date',
            new_name='commitee_member_3_date',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='comittee_member_1',
            new_name='committee_member_1',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='comittee_member_2',
            new_name='committee_member_2',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='comittee_member_3',
            new_name='committee_member_3',
        ),
    ]
