# Generated by Django 3.2 on 2023-01-28 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0072_auto_20230129_0119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='commitee_member_1_date',
            new_name='committee_member_1_date',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='commitee_member_2_date',
            new_name='committee_member_2_date',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='commitee_member_3_date',
            new_name='committee_member_3_date',
        ),
    ]
