# Generated by Django 3.2 on 2023-01-28 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0073_auto_20230129_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='member_name',
            field=models.CharField(max_length=255),
        ),
    ]
