# Generated by Django 3.2 on 2023-01-28 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0074_alter_loan_member_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='date_when_required',
            field=models.DateField(blank=True, null=True),
        ),
    ]
