# Generated by Django 3.2 on 2023-02-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0076_auto_20230211_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='interest_on_loan',
            field=models.IntegerField(default=0),
        ),
    ]
