# Generated by Django 3.2 on 2023-02-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0077_loan_interest_on_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='member_interest_rate',
            field=models.IntegerField(default=0.4),
        ),
        migrations.AlterField(
            model_name='loan',
            name='non_member_interest_rate',
            field=models.IntegerField(default=0.4),
        ),
    ]
