# Generated by Django 3.2 on 2023-02-11 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0078_auto_20230211_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='member_interest_rate',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='non_member_interest_rate',
        ),
    ]
