# Generated by Django 3.2 on 2023-02-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0079_auto_20230211_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='interest_rate',
            field=models.IntegerField(default=0),
        ),
    ]
