# Generated by Django 3.2 on 2023-02-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0080_loan_interest_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='interest_rate',
            field=models.IntegerField(default=1),
        ),
    ]
