# Generated by Django 3.2 on 2023-02-11 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0081_alter_loan_interest_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='interest_rate',
        ),
    ]
