# Generated by Django 3.2 on 2023-02-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0088_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='business_monthly_income',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='member',
            name='proposed_monthly_contribution',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
