# Generated by Django 3.2 on 2023-03-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0091_alter_settings_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialyear',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
