# Generated by Django 3.2 on 2023-03-04 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0093_transaction_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='settings',
        ),
    ]
