# Generated by Django 3.2 on 2024-03-17 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0094_remove_transaction_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('voucher_no', models.IntegerField(unique=True)),
                ('date', models.DateTimeField()),
                ('items_no', models.IntegerField(default=0)),
                ('total_amount', models.IntegerField(default=0)),
                ('requested_by', models.CharField(max_length=255)),
                ('authorized_by', models.CharField(max_length=255)),
                ('paid_by', models.CharField(max_length=255)),
                ('received_by', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VoucherItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('unit_cost', models.IntegerField(default=0)),
                ('total_amount', models.IntegerField(default=0)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.voucher')),
            ],
        ),
    ]
