# Generated by Django 3.2 on 2024-03-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0095_voucher_voucheritem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='authorized_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='paid_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='received_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='requested_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
