# Generated by Django 3.2 on 2024-03-17 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0096_auto_20240317_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucheritem',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
