# Generated by Django 3.2 on 2024-03-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0097_voucheritem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucheritem',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='voucheritem',
            name='unit_cost',
        ),
        migrations.AddField(
            model_name='voucheritem',
            name='cost_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voucheritem',
            name='total_value',
            field=models.IntegerField(default=0),
        ),
    ]
