# Generated by Django 3.2 on 2024-08-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0099_projectfee'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='project_fee',
            field=models.IntegerField(default=0),
        ),
    ]
