# Generated by Django 3.2 on 2024-08-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0100_transaction_project_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='project_fee',
            field=models.IntegerField(default=0),
        ),
    ]
