# Generated by Django 3.2 on 2024-08-23 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0101_member_project_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='NomineesForGFE',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('id_no', models.CharField(max_length=255)),
                ('percentage', models.PositiveIntegerField(default=0)),
                ('date_of_birth', models.DateTimeField()),
                ('mobile_no', models.CharField(max_length=255)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.member')),
            ],
        ),
    ]
