# Generated by Django 3.2 on 2024-08-31 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0102_nomineesforgfe'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomineesfordeposits',
            name='relationship',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='nomineesforgfe',
            name='relationship',
            field=models.CharField(default='', max_length=255),
        ),
    ]
